project/user_course/models.py
import project


class DataBase:
    def __init__(self):
        self.cur = project.db.connection.cursor()

    def page_users(self, page, per_page, search=''):
        if search:
            args = "%" + search + "%", (page - 1) * per_page, per_page,
            sql = "SELECT SQL_CALC_FOUND_ROWS id, name, email, status " \
                  "FROM user WHERE name LIKE %s LIMIT %s, %s;"
        else:
            args = (page - 1) * per_page, per_page
            sql = "SELECT SQL_CALC_FOUND_ROWS id, name, email, status " \
                  "FROM user LIMIT %s, %s;"
        self.cur.execute(sql, args)
        page_users = self.cur.fetchall()
        self.cur.execute("SELECT FOUND_ROWS();")
        total_users = self.cur.fetchone()
        return page_users, total_users

    def user_get(self, user_id):
        sql = "SELECT name, email, phone, mobile_phone, status " \
              "FROM user WHERE id = %s;"
        self.cur.execute(sql, (user_id,))
        return self.cur.fetchone()

    def user_update(self, id, name, email, phone, mobile_phone, status):
        args = name, email, phone, mobile_phone, status, id
        query = "UPDATE user " \
                "SET name=%s, email=%s, phone=%s, mobile_phone=%s, status=%s " \
                "WHERE id=%s"
        self.cur.execute(query, args)
        project.db.connection.commit()

    def user_create(self, name, email, phone, mobile_phone, status):
        args = name, email, phone, mobile_phone, status
        query = "INSERT INTO user(name, email, phone, mobile_phone, status) " \
                "VALUES(%s,%s,%s,%s,%s)"
        self.cur.execute(query, args)
        result = self.cur.lastrowid
        project.db.connection.commit()
        return result

    def user_courses_get(self, user_id):
        sql = "SELECT course_id " \
              "FROM user_course WHERE user_id = %s;"
        self.cur.execute(sql, (user_id,))
        return self.cur.fetchall()

    def user_delete(self, user_id):
        sql = "DELETE FROM user WHERE id = %s;"
        self.cur.execute(sql, (user_id,))
        delete = self.cur.fetchall()
        if len(delete) == 0:
            project.db.connection.commit()

    def user_courses_update(self, user_id, courses_ids):
        self.cur.execute("DELETE FROM user_course WHERE user_id=%s", (user_id,))
        if courses_ids:
            values = [(user_id, c_id) for c_id in courses_ids]
            self.cur.executemany("INSERT INTO user_course VALUES (%s, %s)", values)
        project.db.connection.commit()

    def courses_get(self):
        sql = "SELECT id, name, code " \
              "FROM course;"
        self.cur.execute(sql)
        return self.cur.fetchall()

project/user_course/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired, Email, Length


class UserForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=6, max=50)])
    email = StringField('E-mail', validators=[DataRequired(), Email(), Length(min=6, max=40)])
    phone = StringField('Phone')
    mobile_phone = StringField('Mobile phone')
    status = SelectField('Status', coerce=int, choices=[(0, 'Inactive'), (1, 'Active')], )
    submit = SubmitField('Create')

project/user_course/__init__.py
from flask import Blueprint

user_course = Blueprint('user_course', __name__, template_folder='templates/')
from . import views

project/user_course/views.py
from flask import render_template, flash, request, session, redirect, url_for
from flask_paginate import Pagination
import json
from . import user_course
from .models import DataBase
from .forms import UserForm


@user_course.route("/search", methods=["POST"])
def users_filter():
    session['per_page'] = request.form['per_page']
    session['search'] = request.form['search']
    return redirect(url_for('user_course.users'))


@user_course.route('/', methods=["GET"])
def users():
    search = session.get('search', '')
    page = int(request.args.get('page', 1))
    per_page = int(session.get('per_page', 10))
    page_users = DataBase().page_users(page, per_page, search);
    user_list = page_users[0]
    page_count = page_users[1][0]
    pagination = Pagination(page=page, per_page=per_page, total=page_count,
                            css_framework='bootstrap4')
    return render_template('users.html',
                           user_list=user_list,
                           page=page,
                           per_page=per_page,
                           pagination=pagination,
                           search=search,
                           active_page='users'
                           )


@user_course.route("/courses", methods=["GET"])
def courses():
    course_list = DataBase().courses_get();
    return render_template('courses.html',
                           active_page='courses', course_list=course_list)


@user_course.route("/create", methods=["GET", "POST"])
def user_create():
    form = UserForm(request.form)
    if request.method == 'POST' and form.validate():
        name = request.form['name']
        email = request.form['email']
        phone = request.form['phone']
        mobile_phone = request.form['mobile_phone']
        status = request.form['status']
        try:
            DataBase().user_create(
                name, email, phone, mobile_phone, status)
            flash('User created successfully', 'success')
        except Exception as e:
            flash(e, 'error')

    return render_template('user_new.html', form=form, active_page='users')


@user_course.route("/delete/<int:user_id>")
def user_delete(user_id):
    DataBase().user_delete(user_id)
    return redirect(url_for('user_course.users'))


@user_course.route("/edit/<int:user_id>", methods=["GET", "POST"])
def user_edit(user_id):
    if request.method == 'GET':
        user = DataBase().user_get(user_id)
        form = UserForm()
        form.name.data = user[0]
        form.name(render_kw={'readonly': True})
        form.email.data = user[1]
        form.phone.data = user[2]
        form.mobile_phone.data = user[3]
        form.status.data = user[4]
        user_courses = DataBase().user_courses_get(user_id)
        user_courses = [user_course[0] for user_course in user_courses]
    else:
        form = UserForm(request.form)
        user_courses = json.loads(request.form['user_courses'])
        if form.validate():
            name = request.form['name']
            email = request.form['email']
            phone = request.form['phone']
            mobile_phone = request.form['mobile_phone']
            status = request.form['status']
            try:
                DataBase().user_update(user_id, name, email, phone, mobile_phone, status)
                DataBase().user_courses_update(user_id, user_courses)
                flash('User updated successfully', 'success')
            except Exception as e:
                flash(e, 'error')
    courses = DataBase().courses_get()
    return render_template('user_edit.html',
                           form=form,
                           user_courses=user_courses,
                           courses={course[0]: course[1] for course in courses},
                           user_id=user_id,
                           active_page='users')

project/user_course/templates/courses.html
{% extends 'base.html' %}
{% block title %} Courses {% endblock %}
{% block content %}
    <div class="container-fluid">
            <div class="container text-center">
                <br>
                <h3>COURSES</h3>
                <br>
            </div>
            <div class="container-fluid">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" style="width: 60%">NAME</th>
                    <th scope="col">CODE</th>
                </tr>
                </thead>
                {% for course in course_list %}
                <tr>
                    <td col>
                      {{ course[1] }}
                    </td>
                    <td>
                      {{ course[2] }}
                    </td>
                </tr>
                {% endfor %}

    </div>

{% endblock %}

project/user_course/templates/user_edit.html
{% extends 'base.html' %}
{% block title %} User Edit {% endblock %}
{% block content %}
    <div class="container-fluid">
        <br>
        <div class="row">
            <div class="col-md-3 offset-md-1 text-right">
                <a href={{ url_for('user_course.users') }}>
                    <button class="btn btn-danger" type="button" style="border-radius: 25px; border: 5px;"
                            id="back-btn"><i class="fa fa-chevron-left"></i></button>
                </a>
            </div>
            <div class="col-md-4 text-center">
                <h3>CHANGE USER</h3>
            </div>
            <div class="col-md-2">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div>
                                <a href={{ url_for('user_course.users') }}>
                                    <button type="button" class="btn alert {{ category }}"
                                            style="border-radius: 25px; border: 5px;"
                                            id="flash-btn-{{ category }}">{{ message }}</button>
                                </a>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>
        <br>

        <div class="row justify-content-center">
            <div class="col-md-4">
                <form action="{{ url_for('user_course.user_edit', user_id=user_id) }}" method="POST">
                    {% for field in form %}
                        {% if field.type in ('HiddenField', 'CSRFTokenField') %}
                            {{ field() }}
                        {% elif field.type == 'SubmitField' %}

                        {% else %}
                            <div class="form-group">
                                {% if field.flags.required %}
                                    <span class="text-danger">*</span>
                                {% endif %}
                                {{ field.label(class='control-label') }}
                                {{ field(class = 'form-control form-rounded' ) }}
                                {% if field.errors %}
                                    <span class="text-danger">
                                <ul class="alert errors">
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                                </span>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                    <input type="hidden" id="user_courses" name="user_courses" value="{{ user_courses }}">
                    <label class="control-label" for="sel_courses">Courses</label>
                    <div class="courses_options row align-items-end">
                        <div class="col-10 col-md-10" id="div_courses">
                            <select class="form-control form-rounded" id="sel_courses" name="sel_courses">
                                <option value="">Options..</option>
                                {% for course_id, course_name in courses.items() %}
                                    <option id="option_course_{{ course_id }}"
                                            {% if course_id in user_courses %} hidden {% endif %}
                                            value="{{ course_id }}">{{ course_name }}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="ml-auto col-md-2 text-right">
                            <button type="button" class="btn btn-success form-rounded"
                                    id="add_course" name="add_course" type="button">
                                <i class="fa fa-plus"></i>
                            </button>
                        </div>
                    </div>
                    <div id="div_courses" class="courses_container">
                        {% for user_course in user_courses %}
                            <div id="course_{{ user_course }}" class="row align-items-end">
                                <div class="col-md-6">
                                    <span>{{ courses[user_course] }}</span>
                                </div>
                                <div class="ml-auto text-right">
                                    <button type="button" class="button_remove    btn btn-xs pull-right">
                                        <i class="fa fa-close"></i>
                                    </button>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <br><br>
                    <div class="text-right">
                        <input class="btn btn-success form-rounded" id="submit" name="submit" type="submit"
                               value="Save">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        let user_courses = {{ user_courses|tojson }};
        let sel_courses = $("#sel_courses");

        function check_courses_count() {
            if (user_courses.length >= 5) {
                $('.courses_options').hide();
            } else {
                $('.courses_options').show();
            }
        };

        function add_div(id, name) {
            return (
                `<div id="course_${id}" class="row align-items-end">
                        <div class="col-md-6">
                            <span>${name}</span>
                        </div>
                        <div class="ml-auto text-right">
                            <button type="button" class="button_remove btn btn-xs pull-right">
                                <i class="fa fa-close"></i>
                            </button>
                        </div>
                    </div>`);
        };

        $("#add_course").click(function (event) {
            let sel_courses = $("#sel_courses");
            event.preventDefault();
            if (sel_courses.is(":hidden")) {
                sel_courses.show();
            } else {
                let selected_val = $('#sel_courses option:selected').val();
                if (selected_val == '') {
                    $('#sel_courses').focus();
                } else {
                    $('.courses_container').append(add_div(selected_val,
                        $('#sel_courses option:selected').text()));
                    $('#sel_courses option:selected').hide();
                    $('#sel_courses').val('').change();
                    user_courses.push(parseInt(selected_val));
                    $('input[name=user_courses]').val(JSON.stringify(user_courses));
                    check_courses_count();
                }
            }
        });

        $("document").ready(function () {
            sel_courses.hide();
            check_courses_count();

            $("#name").attr("readonly","true");
            $(document).on("click", ".button_remove", function (e) {
                    e.preventDefault();
                    let parent_id = $(this).parent().parent().attr('id');
                    $('#option_' + parent_id).removeAttr("hidden");
                    user_courses.splice($.inArray($('#option_' + parent_id).val(), user_courses), 1);
                    $('#' + parent_id).remove();
                    check_courses_count();
                    $('input[name=user_courses]').val(JSON.stringify(user_courses));
                }
            );

            $(window).keydown(function (event) {
                if (event.keyCode == 13) {
                    event.preventDefault();
                    return false;
                }
            });

            setTimeout(function () {
                $("#flash-btn-success").click();
            }, 3000);
        });
    </script>

{% endblock %}

project/user_course/templates/user_new.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
    <br>
    <div class="row">
        <div class="col-md-3 offset-md-1 text-right">
            <a href={{ url_for('user_course.users') }}>
                <button class="btn btn-danger" type="button" style="border-radius: 25px; border: 5px;"
                        id="back-btn"><i class="fa fa-chevron-left"></i></button>
            </a>
        </div>
        <div class="col-md-4 text-center">
            <h3>CREATE USER</h3>
        </div>
        <div class="col-md-2">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div>
                            <a href={{ url_for('user_course.users') }}>
                                <button class="btn alert {{ category }}" style="border-radius: 25px; border: 5px;"
                                        id="flash-btn-{{ category }}">{{ message }}</button>
                            </a>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <br>

    <div class="row justify-content-center">
        <div class="col-md-4">
            <form action="{{ url_for('user_course.user_create') }}" method="POST">
                {% for field in form %}
                    {% if field.type in ('HiddenField', 'CSRFTokenField') %}
                        {{ field() }}
                    {% elif field.type == 'SubmitField' %}
                        <div class="text-right">
                            {{ field(class_="btn btn-success form-rounded") }}
                        </div>
                    {% else %}
                        <div class="form-group">
                            {% if field.flags.required %}
                                <span class="text-danger">*</span>
                            {% endif %}
                            {{ field.label(class='control-label') }}
                            {{ field(class = 'form-control form-rounded' ) }}
                            {% if field.errors %}
                                <span class="text-danger">
                                <ul class="alert errors">
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                                </span>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
            </form>
        </div>
    </div>
    <script>
        $("document").ready(function () {
            setTimeout(function () {
                $("#flash-btn-success").click();
            }, 3000);
        });
    </script>

{% endblock %}

project/user_course/templates/users.html
{% extends 'base.html' %}
{% block title %} New User {% endblock %}
{% block content %}
    <div class="container">
        <br>
        <div class="row">
            <div class="container-fluid">
                <form class="form-inline" action="{{ url_for('user_course.users_filter') }}" method="POST">
                    <div class="form-group col-md-1">
                        <a href="{{ url_for('user_course.user_create') }}">
                            <button class="btn btn-danger" type="button" style="border-radius: 25px; border: 5px;"
                                    id="add-btn"><i class="fa fa-plus"></i></button>
                        </a>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="form-group"
                             style="margin-right: -40px; z-index: 3; border-radius: 25px; background-color: transparent;
                    border:none;">
                            <button class="btn btn-success" type="submit" style="border-radius: 25px; border: 5px;"
                                    id="search-btn"><i class="fa fa-search"></i></button>
                        </div>
                        <input class="form-control" type="text" id="search" name="search"
                               placeholder="Search" value="{{ search }}" aria-label="Search"
                               style="padding-left: 40px; border-radius: 25px; z-index: 0">
                    </div>
                    <div class="form-group col-md-3" style="text-align: right">
                        <h3>USERS</h3>
                    </div>
                    <div class="form-group col-sm-3" style="text-align: right">
                        <select name="per_page" name="per_page" class="form-rounded form-control" style="width:100px;">
                            <option {% if per_page == 10 %}selected{% endif %}>10</option>
                            <option {% if per_page == 15 %}selected{% endif %}>15</option>
                            <option {% if per_page == 20 %}selected{% endif %}>20</option>
                        </select>
                    </div>
                </form>
            </div>

        </div>
        <br>
        <div class="container-fluid">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" style="width: 30%">Name</th>
                    <th scope="col" style="width: 30%">E-mail</th>
                    <th scope="col" style="width: 30%">Status</th>
                    <th scope="col"
                    ">Actions</th>
                </tr>
                </thead>
                <tr>
                    {% for user in user_list %}
                        {% set user_id = user[0] -%}
                        {% set is_active = user[3] == 1 %}
                        <tr>
                            <td>
                                {{ user[1] }}
                            </td>
                            <td>
                                {{ user[2] }}
                            </td>
                            <td class="text-{% if is_active %}success{% else %}danger{% endif %}">
                                {% if is_active %}Active{% else %}Inactive{% endif %}
                            </td>
                            <td>
                                <a href="{{ url_for('user_course.user_edit', user_id=user_id) }}">
                                    <button type="button" class="btn btn-success btn-circle"><i
                                            class="fa fa-pencil-square-o"></i></i>
                                    </button>
                                </a>
                                <a href="{{ url_for('user_course.user_delete', user_id=user_id) }}"
                                    onclick="confirm('Are You sure?')">
                                    <button type="button" class="btn btn-danger btn-circle"><i
                                            class="fa fa-trash fa-sm"></i>
                                    </button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="row justify-content-center">
            <div class="col-4">
                {{ pagination.links }}
            </div>
        </div>

{% endblock %}